apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: grafana
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://apache.github.io/incubator-devlake-helm-chart
    chart: devlake
    targetRevision: 1.0.0-beta1
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - grafana
        commonEnvs:
          TZ: "Europe/Berlin"
        grafana:
          env:
            TZ: "Europe/Berlin"
          deployment:
            extraLabels:
              scale-down: "yes"
          securityContext:
            runAsNonRoot: true
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500m
        mysql:
          extraLabels:
            scale-down: "yes"
          securityContext:
            runAsNonRoot: true
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500m
        lake:
          encryptionSecret:
            secret: "ALXWPTWYWWJGEUAXDHLNIMTXLHOXKDAYVAONVCBMUBJFVFUWPABZSOMFEBUALPAEPALESFLSJAFYPKTAZEDCTRDTSZOIAGGALIEDKULLKHIDELBVXRYOGUHIWBNTBPJM"
          image:
            pullPolicy: IfNotPresent
          deployment:
            extraLabels:
              scale-down: "yes"
          securityContext:
            runAsNonRoot: true
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500m
        ui:
          image:
            pullPolicy: IfNotPresent
          deployment:
            extraLabels:
              scale-down: "yes"
          securityContext:
            runAsNonRoot: true
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 500m
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: devlake
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
