apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: ingress-nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.*.*
    helm:
      values: |
        controller:
          hostNetwork: true
          allowSnippetAnnotations: true
          config:
            use-forwarded-headers: true
          service:
            type: ""
          kind: DaemonSet
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
