apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: knative
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DolfenHC/argocd-apps.git
    path: manifests/knative/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: knative
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true