apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: postgres
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.36
    helm:
      values: |
        auth:
          username: admin
          password: admin
        primary:
          service:
            type: NodePort
            nodePorts:
              postgresql: "30032"
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
