apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/upbound/function-patch-and-transform:v0.8.1