apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: crossplane-provider-aws
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DolfenHC/argocd-apps.git
    path: manifests/crossplane-provider-aws/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
